-- MySQL Script generated by MySQL Workbench
-- Fri Jul 20 15:47:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema searchfooddelivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema searchfooddelivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `searchfooddelivery` DEFAULT CHARACTER SET utf8 ;
USE `searchfooddelivery` ;

-- -----------------------------------------------------
-- Table `searchfooddelivery`.`status_restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchfooddelivery`.`status_restaurante` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `searchfooddelivery`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchfooddelivery`.`restaurante` (
  `id_restaurante` INT NOT NULL AUTO_INCREMENT,
  `proprietario` VARCHAR(45) NOT NULL,
  `email_proprietario` VARCHAR(45) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  `celular_proprietario` CHAR(14) NOT NULL,
  `nome_restaurante` VARCHAR(45) NOT NULL,
  `cnpj` CHAR(18) NOT NULL,
  `telefone_restaurante` CHAR(14) NOT NULL,
  `endereco` VARCHAR(80) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto_capa` VARCHAR(45) NOT NULL,
  `tipo_cozinha` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id_restaurante`),
  INDEX `fk_restaurante_status_restaurante_idx` (`status` ASC),
  CONSTRAINT `fk_restaurante_status_restaurante`
    FOREIGN KEY (`status`)
    REFERENCES `searchfooddelivery`.`status_restaurante` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `status_restaurante` (`id_status`, `descricao`) VALUES (NULL, 'Aberto'), (NULL, 'Fechado'), (NULL, 'Bloqueado');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
